# Generated by Django 5.1.2 on 2024-10-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='titulo',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
